#!/bin/bash
# MFL composes by concatenation (`machin encode` joins multiple sources), so a
# build is: every library, then exactly one file with main().
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
MACHIN="${MACHIN:-$HOME/ai/machin/bin/machin}"
MAIN="${1:?usage: build.sh <file-with-main.mfl> [-o out]}"
shift || true
OUT="$(mktemp /tmp/machin-bkn-XXXX.mfl)"

# QuickJS is vendored and linked as a static archive, so the binary stays one
# file. The extern block carries an absolute -L, so it is generated here rather
# than committed with one machine's paths baked in.
"$HERE/vendor/build-qjs.sh"
cat > "$HERE/src/gen_qjs.mfl" <<EOF
// GENERATED by build.sh — do not edit, do not commit.
extern "bknqjs" {
  cflags "-L$HERE/vendor"
  link "bknqjs"
  link "m"
  fn bkn_js_eval(string, string, int, int) string
}
EOF
FW="${MACHIN_FW:-$HOME/ai/machin/framework}"

# `encode` takes every source at once and concatenates them — appending after a
# lone `encode` of the framework yields a file the compiler sees as empty.
if grep -lq "serve(" "$MAIN" 2>/dev/null; then
  "$MACHIN" encode "$FW/machweb.src" "$HERE"/src/*.mfl "$MAIN" > "$OUT"
else
  "$MACHIN" encode "$HERE"/src/*.mfl "$MAIN" > "$OUT"
fi

# The bridge calls the MFL host dispatcher by its mangled C name. That name is
# an implementation detail of machin's codegen, so it is pinned here: if it
# moves, the build stops with an explanation instead of a link error.
# Matched in-shell rather than through a pipe: `grep -q` exits at the first
# hit, and under `pipefail` the writer's SIGPIPE turns a successful match into
# a failed pipeline — which reads as "symbol missing" when it is present.
EMITTED="$("$MACHIN" build "$OUT" --emit-c 2>/dev/null)"
if [[ "$EMITTED" != *"char* mfl_hostCall_0(char* "* ]]; then
  echo "build.sh: machin no longer emits hostCall as mfl_hostCall_0 — vendor/bkn_qjs.c must be updated to match" >&2
  exit 1
fi

# Static by default: the whole point of this build is one file you can copy to
# a host. --static bundles the SQLite amalgamation and links OpenSSL from its
# archives; QuickJS is already a static archive of our own.
STATIC="${BKN_STATIC:-1}"
FLAGS=()
if [ "$STATIC" = "1" ]; then FLAGS+=(--static); fi

if [ "${1:-}" = "-o" ]; then
  "$MACHIN" build "$OUT" "${FLAGS[@]}" -o "$2"
  strip "$2" 2>/dev/null || true
else
  "$MACHIN" run "$OUT"
fi
